### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by Dinika** [Dinika/personal-website#2]
Trello Ticket - https://trello.com/c/eio29bz9/40-make-website-responsive
Mockup - https://www.figma.com/file/3e4BpE4hqRZ7E7zSAF1UtB/Personal-Website?node-id=0%3A1

- Use ems, rems, etc to make website more responsive on mobile devices. 
- Remove the warning dialog (in index.html) and related styles

**Comment by marwanzaky** [comment]
@Dinika assign me this task. I will make the website more responsive on mobile devices.

**Comment by Dinika** [comment]
@marwanzaky Sure!
Give me some time to create a mockup of the responsive design. If it looks like something you'd like to develop, I'll assign the ticket to you.

**Comment by Dinika** [comment]
As promised, [here's](https://www.figma.com/file/3e4BpE4hqRZ7E7zSAF1UtB/Personal-Website?node-id=0%3A1) the mockup for the responsive design. Let me know if there are any issues accessing it.
The mockup is a rough draft, so if you have any suggestions for a better design, do let me know - we could refine the design.

Finally, I'd like to stress that the idea with this ticket is to replace all (or most of) the hardcoded pixel values (like in `fontsize`) with suitable `em` or `rems` unit values. 

If you're still willing to contribute, add a comment here (and thanks :star2: !). I'll assign the trello ticket and the github issue to you.

**Comment by marwanzaky** [comment]
Hi, @Dinika I'm afraid I won't be able to do the task because this morning I took one from another person... I didn't get a response from you for 2 days made me think you weren't interested.

If it wasn't the case I'd still be interested in doing the task. sorry for the inconvenience 🙏

**Comment by Dinika** [comment]
No problems! Happy coding :)

**Comment by ReangeloJ** [comment]
I just viewed your website and saw that is still hasn't been done. Do you still need some help?

**Comment by Dinika** [comment]
@ReangeloJ Yep. Any and all help is welcome :)

**Comment by ReangeloJ** [comment]
> @ReangeloJ Yep. Any and all help is welcome :)

Aight sure will get to it then!

**Comment by Dinika** [comment]
Thanks @ReangeloJ. Just a reminder - [here's](https://www.figma.com/file/3e4BpE4hqRZ7E7zSAF1UtB/Personal-Website?node-id=0%3A1) the link to the mockup for the responsive design. I will go ahead and assign [this trello ticket](https://trello.com/c/eio29bz9/40-make-website-responsive) to you.

If you think it's easier to make different PRs for making different sections of the website responsive, let me know. I'll split the tickets accordingly. That way the PRs will also be more manageable to review and merge :)

**Comment by Dinika** [comment]
> > @ReangeloJ Yep. Any and all help is welcome :)
> > I see that it is written in (Vue?). Is it okay if its redone with React/Next? Im not very familiar with Vue

@ReangeloJ The website is using vanilla [web components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components). There are no javascript dependencies in the project (so no react, vue, etc), and I would really like to keep it that way. 

Web components are actually really cool and a native technology that almost all web browsers support now. I'm willing to clarify any doubts/issues that you may have. I also understand though if you're not looking to work with it (web components) at this time, in which case, please let me know. No pressure!

**Comment by ReangeloJ** [comment]
> > > @ReangeloJ Yep. Any and all help is welcome :)
> 
> > > I see that it is written in (Vue?). Is it okay if its redone with React/Next? Im not very familiar with Vue
> 
> 
> 
> @ReangeloJ The website is using vanilla [web components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components). There are no javascript dependencies in the project (so no react, vue, etc), and I would really like to keep it that way. 
> 
> 
> 
> Web components are actually really cool and a native technology that almost all web browsers support now. I'm willing to clarify any doubts/issues that you may have. I also understand though if you're not looking to work with it (web components) at this time, in which case, please let me know. No pressure! 


Oeps I just deleted my comments because I indeed saw that it is web components that you are using. Okay if its just writing css then it's still quite easy to do. Will start after the weekend!

**Comment by Dinika** [comment]
@ReangeloJ [This PR](https://github.com/Dinika/personal-website/pull/4) can be used to get an idea of how to open/close the responsive menu.

**Comment by Dinika** [comment]
@ReangeloJ Just double checking - are you still working on this? I have some time on my hands now and can take it over if you are busy.

**Comment by Dinika** [comment]
The last few commits to the source code address this issue, so closing this as done.
